site_name: Mon site MkDocs sur Read the Docs
site_url: https://my-mkdocs-site-on-rtd.readthedocs.io/
nav:
  - Accueil: index.md
  - Conférences:
    - Conférence PyLadiesCon: conferences/pyladiescon.md
    - Conférence PyConFR: conferences/pyconfr.md
theme:
  name: material
